### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED while trying to query the API

### ISSUE THREAD

**Issue by amarpreetsaini** [Geotab/mygeotab-python#178]
Getting SSLError on running below code
```
import mygeotab
api = mygeotab.API(username='user@example.com', password='password', database='database')
api.authenticate()
api.get('Device', resultsLimit=1)
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='my625.geotab.com', port=443): Max retries exceeded with url: /apiv1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),))

**Comment by amarpreetsaini** [comment]
@aaront Thanks a lot for information

**Comment by sheepdogapproved** [comment]
I received this same error today.

**Comment by aaront** [comment]
@sheepdogapproved Hi there, do you happen to have the error/traceback similar to what Amarpreet posted previously?

**Comment by sheepdogapproved** [comment]
I have narrowed this down to that this only happens when I am logged into my corporate VPN via Cisco AnyConnect. I can hit the https test link for the API and can use the code runner fine, so it appears to be specific to this wrapper in Python. No VPN, the wrapper and code works fine. Trying to figure out where to even start to diagnose it. I need to be on the VPN to interact with our on-prem SQL Server warehouse as well. 

This is the last increment of the traceback. 

ConnectionError: HTTPSConnectionPool(host='my.geotab.com', port=443): Max retries exceeded with url: /apiv1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000B514A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by aaront** [comment]
@sheepdogapproved Might be a firewall issue on your end? Are you able to access https://my.geotab.com from a browser within your VPN?

**Comment by sheepdogapproved** [comment]
It most definitely is a firewall issue, but it's strange in that it's only affecting calls from Python.

I can log into MyGeotab fine, and can make the simple Version call one-liner in Chrome and it returns. So far as I can tell, it's only affecting Python inside the VPN - as soon as I sign off it works like a charm.

**Comment by thedaniel** [comment]
your employer is probably MITMing your SSL, get a valid cert file from certifi, find the cert your employer is using to break encryption, and add it to that file, and use it as the verify flag in requests.get.

if you're using a mac, the reason things work everywhere but python is that it is (i assume) not getting certs from the macos keychain, which is where your employer-installed certs are
