### ISSUE TITLE
Grabbing Count of Zone entries from api 

### ISSUE THREAD

**Issue by JLIVE101** [Geotab/mygeotab-python#3]
Hi Aaron, thanks so much for the help last week, i was able to write a program to grab to grab the fuel information. I have another inquiry. This time i checked the runner and forums but couldn't find anything. I was wondering what parameters i need to send to the api in order to get the zones a driver has entered for the day. On geotab i would go to zones & messages ->  Customer visits and search by all vehicles/zones and set the date to today. I would get each zone a driver has went into and the arrival / departure time.

What call is being made to retrieve this information? I looked in the url and saw "#CustomerVisits" but thats not a type i could search by.

**Comment by aaront** [comment]
@JLIVE101 Customer visits are actual stops in the zone. Is that what you're asking about? Or is it any entry into a zone?

Either or, you can create 2 new rules in the MyGeotab UI that does this for a particular zone type (ie. Customer), one for entering and one for exiting a ZoneType:

![screen shot 2015-12-14 at 11 26 42 pm](https://cloud.githubusercontent.com/assets/50092/11802063/2e78b924-a2ba-11e5-8acf-31e2bd1efecc.png)

Then, all you would need to do is grab exceptions for those rules to determine enter/exit times:

(didn't test the below, but should be almost right :wink:)

```python
from datetime import datetime, timedelta

entering_rule = api.search('Rule', name='Custom Entering Customer Zone')[0]
exiting_zone = api.search('Rule', name='Custom Exiting Customer Zone')[0]
device = api.search('Device', name='My Device')

end = datetime.utcnow()
start = end - timedelta(days=1)

entering_exceptions = api.search('ExceptionEvent', 
                                 ruleSearch=dict(id=entering_rule['id']),
                                 deviceSearch=dict(id=device['id']),
                                 fromDate=start,
                                 toDate=end)

exiting_exceptions = api.search('ExceptionEvent', 
                                ruleSearch=dict(id=exiting_rule['id']),
                                deviceSearch=dict(id=device['id']),
                                fromDate=start,
                                toDate=end)
```

The concept was similar to a question [asked in the forums](https://helpdesk.geotab.com/entries/22657859-Zone-entry-exit-times) (even though we don't officially support this library in there). In the future, don't hesitate to post over on the official forums if you have conceptual questions like this one, you're more likely to get an answer much quicker than on here (because I work on this library in my spare time as a hobby project).

**Comment by JLIVE101** [comment]
you're a lot of help, i also asked on the forums and i was able to find out how to set up the entry and exits. You helped me figure it out how to grab it. Almost defeats the purpose of learning but i still appreciate all the help lol . Thanks a bunch. It really means a lot.
